name: Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  discord-update:
    name: Update discord data.
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Setup node.
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run script.
        run: |
          npm ci
          npm run update
        working-directory: "./update"
        env:
          DISCORD_TOKEN: "${{ secrets.DISCORD_TOKEN }}"

      - name: Push updates.
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add data/jads-results.json
            git commit -m "Update discord data."
            git push
          fi
